import R from 'ramda';
import H from './bus/hand';

export default {
  rules: [
    [1, 88, '四风会', 'Big Four Winds', '和牌中，有东、南、西、北四副刻子（杠）', 'Pungs or Kongs of all four Wind Tiles.',
      [['f1', 'f1', 'f1'], ['f2', 'f2', 'f2'], ['f3', 'f3', 'f3'], ['f4', 'f4', 'f4']], [4, 0, H.isWind], [38, 49, 60, 61, 73, 75]],
    [2, 88, '大三元', 'Big Three Dragons', '和牌中，有中、发、白三副刻子（杠）', 'Pungs or Kongs of all three Dragon Tiles',
      [['j1', 'j1', 'j1'], ['j2', 'j2', 'j2'], ['j3', 'j3', 'j3']], [3, 0, H.isArrow], [54, 59, 73]],
    [3, 88, '绿一色', 'All Green', '由“23468”条及“发”字中的任何牌组成的和牌',
      'A hand in which the chows, pungs and pair(s) are made up solely of "green" tiles: 2 Bam, 3 Bam, 4 Bam, 6 Bam, 8 Bam, and Green Dragon.',
      [['t2', 't2', 't2'], ['t6', 't6', 't6'], ['t8', 't8', 't8'], ['j2', 'j2', 'j2'], ['t3', 't3']], [0, 0, 't2t3t4t6t8j2']],
    [4, 88, '九莲宝灯', 'Nine Gates', '由一种花色序数牌按“1112345678999”组成的特定牌型，见同花色任何一张序数牌即成和牌（自摸加计不求人）',
      'Holding the 1,1,1,2,3,4,5,6,7,8,9,9,9 tiles in any one of the suits, creating the nine-sided wait of 1,2,3,4,5,6,7,8,9. (Fully Concealed may be combined if Self-Drawn).',
      [['w1', 'w1'], ['w1', 'w2', 'w3'], ['w4', 'w5', 'w6'], ['w7', 'w8', 'w9'], ['w9', 'w9']], [H.isLotus], [22, 62, 73]],
    [5, 88, '四杠', 'Four Kongs', '和牌中，有四副杠牌（暗杠加计）', 'Any hand that includes four kongs. They may be concealed or melded.',
      [['b3', 'b3', 'b3', 'b3'], ['t5', 't5', 't5', 't5'], ['w1', 'w1', 'w1', 'w1'], ['j1', 'j1', 'j1', 'j1']], [4, H.isG], [17, 49, 57, 74, 79]],
    [6, 88, '连七对', 'Seven Shifted Pairs', '由一种花色序数相连的七个对子组成的和牌（自摸加计不求人）',
      'A hand formed by seven pairs of the same suit, each shifted one up from the last. (Fully Concealed may be combined if Self-Drawn).',
      [['b2', 'b2'], ['b3', 'b3'], ['b4', 'b4'], ['b5', 'b5'], ['b6', 'b6'], ['b7', 'b7'], ['b8', 'b8']], [H.is7SeqPairs], [19, 22, 62, 79]],
    [7, 88, '十三幺', 'Thirteen Orphans', '由三种序数牌的一、九牌、七种字牌及其中一对作将组成的和牌（自摸加计不求人）',
      'A hand created by singles of any 12 of the 1, 9, and Honor tiles, along With a pair of the 13th. (Fully Concealed may be combined if Self-Drawn).',
      [['w1', 'w9', 't1'], ['t9', 'b1', 'b9'], ['f1', 'f2', 'f3', 'f4'], ['j1', 'j2', 'j3']], [H.is13Y], [18, 52, 55, 62, 79]],
    [8, 64, '清幺九', 'All Terminals', '由序数牌一、九刻子（杠）、将牌组成的和牌',
      'The pair(s), Pungs or Kongs are all made up of 1 or 9 Number Tiles, without Honor Tiles.',
      [['w1', 'w1', 'w1'], ['w9', 'w9', 'w9'], ['t1', 't1', 't1'], ['b9', 'b9', 'b9'], ['t9', 't9']], [0, 0, H.isY], [49, 55, 73, 76]],
    [9, 64, '小四风会', 'Little Four Winds', '和牌中，有风牌的三副刻子（杠）、另一种风牌作将牌',
      'A hand that includes three pungs or Kongs Of Wind Tiles, and a pair of the fourth Wind.',
      [['f1', 'f1', 'f1'], ['f2', 'f2', 'f2'], ['f3', 'f3', 'f3'], ['f4', 'f4']], [[3, 0, H.isWind], [11, 0, H.isWind]], [38, 73]],
    [10, 64, '小三元', 'Little Three Dragons', '和牌中，有箭牌的两副刻子（杠）、另一种箭牌作将牌',
      'A hand that includes two Pungs or Kongs of the Dragon Tiles, and a pair of the third Dragon.',
      [['j1', 'j1', 'j1'], ['j2', 'j2', 'j2'], ['j3', 'j3']], [[2, 0, H.isArrow], [11, 0, H.isArrow]], [54, 59]],
    [11, 64, '字一色', 'All Honors', '由字牌的刻子（杠）、将牌组成的和牌', 'The pair(s), pungs or Kongs are all made up of Honor Tiles.',
      [['f1', 'f1', 'f1'], ['j2', 'j2', 'j2'], ['f3', 'f3', 'f3'], ['f4', 'f4', 'f4'], ['j1', 'j1']], [0, 0, H.isWord], [49, 55, 73]],
    [12, 64, '四暗刻', 'Four Concealed Pungs', '和牌中，有四副暗刻（或暗杠；自摸加计不求人）',
      'A hand that includes four Concealed Pungs or Kongs (achieved without melding). (Fully Concealed may be combined if Self-Drawn).',
      [['b3', 'b3', 'b3', -1], ['t5', 't5', 't5', -1], ['w1', 'w1', 'w1', -1], ['j1', 'j1', 'j1', -1]], [4, [H.isA, H.isKG]], [49, 62]],
    [13, 64, '一色双龙会', 'Pure Terminal Chows', '一种花色的两个老少副、5 作将牌',
      'A hand consisting of two each of the lower and upper terminal Chows in one suit only, and a pair of fives in the same suit.',
      [['w1', 'w2', 'w3'], ['w1', 'w2', 'w3'], ['w5', 'w5'], ['w7', 'w8', 'w9'], ['w7', 'w8', 'w9']],
      [[H.isPure], [2, H.isYoung], [2, H.isOld], [11, 0, H.is5]], [19, 22, 63, 69, 72, 76]],
    [14, 48, '一色四同顺', 'Quadruple Chow', '一种花色四副序数相同的顺子', 'Four chows of the same continuous number sequence in the same suit.',
      [['w1', 'w2', 'w3'], ['w1', 'w2', 'w3'], ['w1', 'w2', 'w3'], ['w1', 'w2', 'w3']], [H.is1ColorNSameS(4)], [23, 64, 69]],
    [15, 48, '一色四节高', 'Four Pure Shifted Pungs', '一种花色四副依次递增一个序数的刻子（杠）',
      'Four Pungs (or Kongs) in the same suit, each shifted one up from the last.',
      [['w2', 'w2', 'w2'], ['w3', 'w3', 'w3'], ['w4', 'w4', 'w4'], ['w5', 'w5', 'w5']],
      [H.isNColor3Sth(1, 2, R.both(H.lenEq(4), H.isSeq))], [24, 49]],
    [16, 32, '一色四步高', 'Four Pure Shifted Chows', '一种花色四副依次递增一个或两个序数的顺子',
      'Four chows in one suit, each shifted up 1 or 2 numbers from the last, but not a combination of both.',
      [['w1', 'w2', 'w3'], ['w2', 'w3', 'w4'], ['w3', 'w4', 'w5'], ['w4', 'w5', 'w6'], ['ww'], ['w1', 'w2', 'w3'], ['w3', 'w4', 'w5'], ['w5', 'w6', 'w7'], ['w7', 'w8', 'w9']],
      [H.isNColor3Sth(1, 1, R.both(H.lenEq(4), H.isSeq1or2))], [71, 72]],
    [17, 32, '三杠', 'Three Kongs', '和牌中，有三副杠牌（暗杠加计）', 'A hand containing three Kongs. (Points for concealment may be added).',
      [['b3', 'b3', 'b3', 'b3'], ['t5', 't5', 't5', 't5'], ['j1', 'j1', 'j1', 'j1']], [3, H.isG], [57, 74]],
    [18, 32, '混幺九', 'All Terminals and Honors', '由字牌和序数牌一、九刻子（杠）、将牌组成的和牌',
      'The pair(s), Pungs or Kongs are all made up of 1 or 9 Number Tiles and Honor Tiles.',
      [['w1', 'w1', 'w1'], ['b9', 'b9', 'b9'], ['t1', 't1', 't1'], ['f2', 'f2', 'f2'], ['t9', 't9']],
      [[0, 0, H.isYOrWord], [-1, 0, H.isY], [-1, 0, H.isWord]], [49, 55, 73]],
    [19, 24, '七对', 'Seven Pairs', '由七个对子组成的和牌（自摸加计不求人）',
      'A hand formed by seven pairs. (Fully Concealed may be combined if Self-Drawn).',
      [['w5', 'w5'], ['b8', 'b8'], ['t3', 't3'], ['f2', 'f2'], ['t9', 't9'], ['j1', 'j1'], ['w2', 'w2']], [H.is7Pairs], [62, 66, 73, 79]],
    [20, 24, '七星不靠', 'Greater Honors and Knitted Tiles',
      '必须有七个单张的东、南、西、北、中、发、白，加上三种花色数位按147、 258、369 中的七张序数牌组成的没有将牌的和牌（自摸加计不求人）',
      'Formed by seven single honors and singles of suit tiles belonging to separate Knitted sequences (for example, 1-4-7 of Bamboos, 2-5-8 of Characters, and 3-6-9 of Dots). Fully Concealed may be combined if Self-Drawn.',
      [['f1', 'f2', 'f3', 'f4'], ['j1', 'j2', 'j3'], ['w2', 'w5', 'w8'], ['t1', 't4'], ['b3', 'b9']], [H.is7Star(7)], [52, 62]],
    [21, 24, '全双刻', 'All Even Pungs', '由2、4、6、8 序数牌的刻子（杠）、将牌组成的和牌',
      'A hand formed with Pungs or Kongs of 2, 4, 6, and 8 tiles, with a pair of the same.',
      [['w2', 'w2', 'w2'], ['t8', 't8', 't8'], ['b4', 'b4', 'b4'], ['b6', 'b6', 'b6'], ['w6', 'w6']], [0, 0, H.isEven], [49, 68]],
    [22, 24, '清一色', 'Full Flush', '由一种花色序数牌组成的和牌', 'A hand formed entirely of a single suit.',
      [['w2', 'w3', 'w4'], ['w6', 'w6', 'w6'], ['w7', 'w8', 'w9'], ['w5', 'w5', 'w5'], ['w1', 'w1']], [H.isPure], [76]],
    [23, 24, '一色三同顺', 'Pure Triple Chow', '和牌中，有一种花色三副序数相同的顺子',
      'Three chows of the same numerical sequence and in the same suit.',
      [['w1', 'w2', 'w3'], ['w1', 'w2', 'w3'], ['w1', 'w2', 'w3']], [H.is1ColorNSameS(3)], [69]],
    [24, 24, '一色三节高', 'Pure Shifted Pungs', '和牌中，有一种花色三副依次递增一个序数的刻子（杠）',
      'Three Pungs or Kongs of the same suit, each shifted one up from the last.',
      [['w2', 'w2', 'w2'], ['w3', 'w3', 'w3'], ['w4', 'w4', 'w4']], [H.isNColor3Sth(1, 2, R.both(H.lenEq(3), H.isSeq))]],
    [25, 24, '全大', 'Upper Tiles', '由序数牌7、8、9 组成的和牌', 'A hand consisting entirely of 7, 8, and 9 tiles.',
      [['w7', 'w8', 'w9'], ['t7', 't8', 't9'], ['b8', 'b8', 'b8'], ['b9', 'b9', 'b9'], ['w8', 'w8']], [0, 0, H.isBig], [36, 76]],
    [26, 24, '全中', 'Middle Tiles', '由序数牌4、5、6 组成的和牌', 'A hand consisting entirely of 4, 5, and 6 tiles.',
      [['w4', 'w5', 'w6'], ['t4', 't5', 't6'], ['b4', 'b5', 'b6'], ['b4', 'b5', 'b6'], ['w5', 'w5']], [0, 0, H.isMid], [68, 76]],
    [27, 24, '全小', 'Lower Tiles', '由序数牌1、2、3 组成的和牌', 'A hand consisting entirely of l, 2, and 3 tiles.',
      [['w1', 'w2', 'w3'], ['t1', 't1', 't1'], ['b1', 'b2', 'b3'], ['b1', 'b2', 'b3'], ['w3', 'w3']], [0, 0, H.isSmall], [37, 76]],
    [28, 16, '清龙', 'Pure Straight', '和牌中，有同花色123、456、789 相连的序数牌',
      'A hand using one each of all the numbers 1 through 9 from any one suit, forming three consecutive chows.',
      [['w1', 'w2', 'w3'], ['w4', 'w5', 'w6'], ['w7', 'w8', 'w9']], [H.isNColor3Sth(1, 1, H.is1to9)], [71, 72]],
    [29, 16, '三色双龙会', 'Three-Suited Terminal Chows', '两种花色两个老少副、另一种花色5 作将的和牌',
      'A hand consisting of 1-2-3 and 7-8-9 in one suit (Two Terminal Chows), 1-2-3 and 7-8-9 in another suit, and a pair of fives in the remaining suit.',
      [['w1', 'w2', 'w3'], ['w7', 'w8', 'w9'], ['t5', 't5'], ['b1', 'b2', 'b3'], ['b7', 'b8', 'b9']],
      [H.is3Color2Dragon], [63, 70, 72, 76]],
    [30, 16, '一色三步高', 'Pure Shifted Chows', '和牌中，有一种花色三副依次递增一个或两个序数的顺子',
      'Three chows in one suit, each shifted either one or two numbers up from the last, but not a combination of both.',
      [['w2', 'w3', 'w4'], ['w3', 'w4', 'w5'], ['w4', 'w5', 'w6'], ['ww'], ['w1', 'w2', 'w3'], ['w3', 'w4', 'w5'], ['w5', 'w6', 'w7']],
      [H.isNColor3Sth(1, 1, R.both(H.lenEq(3), H.isSeq1or2))]],
    [31, 16, '全带五', 'All Fives', '每副牌及将牌中必须有5 的序数牌',
      'A hand in which every set (chow , pung, kong, pair) includes the number "5"',
      [['w5', 'w6', 'w7'], ['t3', 't4', 't5'], ['b5', 'b5', 'b5'], ['b4', 'b5', 'b6'], ['w5', 'w5']], [0, -1, H.is5], [68]],
    [32, 16, '三同刻', 'Triple Pung', '和牌中，有三副序数相同的刻子（杠）', 'Three Pungs (or Kongs) of the same number in each suit.',
      [['w2', 'w2', 'w2'], ['t2', 't2', 't2'], ['b2', 'b2', 'b2']], [H.isNSameK(3)]],
    [33, 16, '三暗刻', 'Three Concealed Pungs', '和牌中，有三副暗刻（暗杠）', 'Three Concealed pungs or Kongs (achieved without melding).',
      [['b3', 'b3', 'b3', -1], ['t5', 't5', 't5', -1], ['j1', 'j1', 'j1', -1]], [3, [H.isA, H.isKG]]],
    [34, 12, '全不靠', 'Lesser Honors and Knitted Tiles',
      '由三种花色147、258、369 不能错位的序数牌及东、南、西、北、中、发、白中任何十四张单张牌组成的和牌（自摸加计不求人）',
      'Formed by single honors, and singles of suit tiles belonging to separate Knitted sequences (for example, 1-4-7 of Bamboo, 2-5-8 of Characters, and 3-6-9 of Dots - each of the 3 suits must belong to a different Knitted sequence, but not necessarily in this order). Fully Concealed may be combined if Self-Drawn.',
      [['f1', 'f2', 'f3'], ['j1', 'j2', 'j3'], ['w2', 'w5', 'w8'], ['t1', 't4', 't7'], ['b3', 'b9']], [H.is7Star(4)], [52, 62]],
    [35, 12, '组合龙', 'Knitted Straight', '和牌中，有三种花色的147、258、369 不能错位的序数牌（特殊顺子）',
      'A special Straight which is formed not with standard chows but with 3 different Knitted sequences. For example, 1-4-7 of Dots, 2-5-8 of Characters, and 3-6-9 of Bamboos - but not necessarily in the order in this example.',
      [['w1', 'w4', 'w7'], ['t2', 't5', 't8'], ['b3', 'b6', 'b9']], [H.isZigZag]],
    [36, 12, '大于五', 'Upper Four', '由序数牌6、7、8、9 组成的和牌', 'A hand created with suit tiles 6 through 9.',
      [['w6', 'w7', 'w8'], ['t7', 't8', 't9'], ['b7', 'b7', 'b7'], ['b6', 'b7', 'b8'], ['w9', 'w9']], [0, 0, H.is6789], [76]],
    [37, 12, '小于五', 'Lower Four', '由序数牌1、2、3、4 组成的和牌', 'A hand created with suit tiles I through 4.',
      [['w1', 'w2', 'w3'], ['t2', 't3', 't4'], ['b2', 'b2', 'b2'], ['b2', 'b3', 'b4'], ['w4', 'w4']], [0, 0, H.is1234], [76]],
    [38, 12, '三风刻', 'Big Three Winds', '和牌中，有三副风刻（杠）',
      'A hand that includes one pung (or kong) of each of the three winds.',
      [['f1', 'f1', 'f1'], ['f2', 'f2', 'f2'], ['f3', 'f3', 'f3']], [3, 0, H.isWind]],
    [39, 8, '花龙', 'Mixed Straight', '和牌中，有三种花色的三副顺子连接成123、456、789',
      'A straight (tiles 1 through 9) formed by chows from all three suits.',
      [['w1', 'w2', 'w3'], ['t4', 't5', 't6'], ['b7', 'b8', 'b9']], [H.isNColor3Sth(3, 1, H.is1to9)]],
    [40, 8, '推不倒', 'Reversible Tiles', '由牌面图形没有上下区别的牌组成的和牌。包括1234589饼、245689 条、白板',
      'A hand created entirely with those tiles which are vertically symmetrical, which means the carved designs look the same if you turn them upside-down. These tiles are the 1, 2, 3, 4, 5, 8, and 9 Dots, the 2, 4, 5, 6, 8, and 9 Bams, and the White Dragon.',
      [['t4', 't4', 't4'], ['t8', 't8', 't8'], ['b1', 'b2', 'b3'], ['b5', 'b5', 'b5'], ['j3', 'j3']],
      [0, 0, 't2t4t5t6t8t9b1b2b3b4b5b8b9j3'], [75]],
    [41, 8, '三色三同顺', 'Mixed Triple Chow', '和牌中，有三种花色三副序数相同的顺子',
      'Three chows of the same numerical sequence, one in each suit.',
      [['w2', 'w3', 'w4'], ['t2', 't3', 't4'], ['b2', 'b3', 'b4']], [H.isNColorNSameS(3)]],
    [42, 8, '三色三节高', 'Mixed Shifted Pungs', '和牌中，有三种花色三副依次递增一个序数的刻子（杠）',
      'Three pungs (or kongs), one in each suit, each shifted up one number from the last.',
      [['w2', 'w2', 'w2'], ['t3', 't3', 't3'], ['b4', 'b4', 'b4']], [H.isNColor3Sth(3, 2, H.isSeq)]],
    [43, 8, '无番和', 'Chicken Hand', '和牌后，数不出任何番种分（花牌不计算在内）',
      'A hand that would otherwise earn 0 points (excluding the Flower Tiles).', []],
    [44, 8, '妙手回春', 'Last Tile Draw', '自摸牌墙上最后一张牌和牌（不计自摸）',
      'Going out (making mahjong) on a pick of the very last tile of the wall. (Points for Self-Drawn may not be combined.)', []],
    [45, 8, '海底捞月', 'Last Tile Claim', '和打出的最后一张牌',
      'Going out (making mahjong) off the discard which is the last tile in the game.', []],
    [46, 8, '杠上开花', 'Out With Replacement Tile', '杠牌时，从牌墙补上一张牌成和牌。杠牌加计，不计自摸；杠来花牌再补花成和不计杠上开花，可计自摸',
      'Going out (making mahjong) on the replacement tile drawn after achieving a kong (not on a Flower replacement). When a Flower Tile is taken after Konging, and upon winning on the Flower replacement, points for Self-Drawn may be added (but Out With Replacement Tile does not apply in this case).',
      [['w2', 'w2', 'w2', 'w2', 3]]],
    [47, 8, '抢杠和', 'Robbing The Kong', '和他人自抓开明杠的牌（不计和绝张）',
      'Winning off the tile that somebody adds to a melded pung (to create a Kong). (The points for Last Tile may not be combined.)',
      [['w2', 'w2', 'w2', 'w2', 3]]],
    [48, 8, '双暗杠', 'Two Concealed Kongs', '和牌中，有两副暗杠', 'A hand that includes two Concealed Kongs.',
      [['w2', 'w2', 'w2', 'w2', -1], ['t8', 't8', 't8', 't8', -1]], [2, [H.isA, H.isG]]],
    [49, 6, '碰碰和', 'All Pungs', '由四副刻子（杠）、将牌组成的和牌', 'A hand formed by four Pungs (or Kongs) and one pair.',
      [['w2', 'w2', 'w2'], ['t4', 't4', 't4'], ['b7', 'b7', 'b7'], ['f3', 'f3', 'f3'], ['t9', 't9']], [4, H.isKG]],
    [50, 6, '混一色', 'Half Flush', '由一种花色序数牌及字牌组成的和牌',
      'A hand formed by tiles from any one of the three suits, in combination with Honor tiles.',
      [['w2', 'w3', 'w4'], ['w6', 'w6', 'w6'], ['w7', 'w8', 'w9'], ['j1', 'j1', 'j1'], ['w1', 'w1']], [H.isHalfPure]],
    [51, 6, '三色三步高', 'Mixed Shifted Chows', '和牌中，有三种花色三副依次递增一个序数的顺子',
      'Three chows, one in each suit, each shifted up one number from the last.',
      [['w2', 'w3', 'w4'], ['t3', 't4', 't5'], ['b4', 'b5', 'b6']], [H.isNColor3Sth(3, 1, H.isSeq)]],
    [52, 6, '五门齐', 'All Types', '由三种花色序数牌、风牌、箭牌组成的和牌',
      'A hand in which each of the five sets (pungs, kongs, chows, pairs) is composed of a different type of tile (Characters, Bamboo, Dots, and Dragons).',
      [['w2', 'w2', 'w2'], ['t1', 't2', 't3'], ['b6', 'b7', 'b8'], ['j2', 'j2', 'j2'], ['f1', 'f1']], [H.is5Suits]],
    [53, 6, '全求人', 'Melded Hand', '四副牌组全是吃、碰（明杠），和他人打出的牌',
      'Every set in the hand (chow, pung, kong, and pair) must be completed with tiles discarded by other players. All sets must be exposed, and the player goes out on a single wait off another player.',
      [], [0, H.isM], [79]],
    [54, 6, '双箭刻', 'Two Dragons Pungs', '和牌中，有两副箭刻（杠）', 'Two pungs (or kongs) of Dragon tiles.',
      [['j1', 'j1', 'j1'], ['j2', 'j2', 'j2']], [2, H.isArrowKG]],
    [55, 4, '全带幺', 'Outside Hand', '每副牌及将牌中都有幺九牌', 'A hand that includes terminals and honors in each set, including the pair.',
      [['w1', 'w2', 'w3'], ['t7', 't8', 't9'], ['f2', 'f2', 'f2'], ['b1', 'b1', 'b1'], ['b9', 'b9']], [0, -1, H.isYOrWord]],
    [56, 4, '不求人', 'Fully Concealed Hand', '没有吃牌、碰牌、明杠，自摸和牌',
      'A hand that a player completes without any melds, and wins by Self-Draw.',
      [], [0, H.isA], [62, 80]],
    [57, 4, '双明杠', 'Two Melded Kongs', '和牌中，有两副明杠（一明杠与一暗杠计6 分）',
      'A hand that includes two Melded Kongs. One Melded Kong and one Concealed Kong are 6 points.',
      [['w2', 'w2', 'w2', 'w2'], ['t5', 't5', 't5', 't5']], [2, [H.isM, H.isG]]],
    [58, 4, '和绝张', 'Last Tile', '和牌池、桌面已亮明三张所剩的第四张相同的牌',
      'Winning on a tile that is the last Of its kind. (It must be clear to all players based on the discards and exposures.)',
      [['w2', 'w2', 'w2', 'w2', 3]]],
    [59, 2, '箭刻', 'Dragon Pung', '由中、发、白三张相同的牌组成的刻子（杠）', 'A Pung or Kong of Dragon Tiles.',
      [['j2', 'j2', 'j2']], [1, H.isArrowKG], [73]],
    [60, 2, '圈风刻', 'Prevalent Wind', '与圈风相同的风刻（杠）',
      'A pung or Kong of the Wind Tile corresponding to the current Prevalent Wind.',
      [['f1', 'f1', 'f1']]],
    [61, 2, '门风刻', 'Seat Wind', '与本门风相同的风刻（杠）',
      'A Pung or Kong of the Wind Tile corresponding to the player\'s Seat position at the table. (Dealer is East; proceeding counter-clockwise from the Dealer, other players\' seats are South, West, North.)',
      [['f1', 'f1', 'f1']]],
    [62, 2, '门前清', 'Concealed Hand', '没有吃牌、碰牌（明杠）的和牌',
      'Having a concealed hand (no melded sets) and winning by discard.',
      [], [0, H.isA]],
    [63, 2, '平和', 'All Chows', '由四副顺子及序数牌作将组成的和牌',
      'A hand consisting of all chows, with no Honors.',
      [['w2', 'w3', 'w4'], ['t1', 't2', 't3'], ['b5', 'b6', 'b7'], ['t3', 't4', 't5'], ['b6', 'b6']], [[4, H.isS], [11, 0, H.isDigit]], [76]],
    [64, 2, '四归一', 'Tile Hog', '和牌中，有四张相同的牌（不包括杠牌）',
      'Using all four of a single suit tile, without using them as a Kong.',
      [['w2', 'w2', 'w2'], ['w2', 'b3', 'b4']], [H.is4in1]],
    [65, 2, '双同刻', 'Double Pung', '和牌中，有两副序数相同的刻子（杠）',
      'Two Pungs (or Kongs) of the same number in two different suits.',
      [['w2', 'w2', 'w2'], ['t2', 't2', 't2']], [H.isNSameK(2)]],
    [66, 2, '双暗刻', 'Two Concealed Pungs', '和牌中，有两副暗刻（暗杠）', 'Two Pungs achieved without melding.',
      [['w2', 'w2', 'w2', -1], ['t5', 't5', 't5', -1]], [2, [H.isA, H.isKG]]],
    [67, 2, '暗杠', 'Concealed Kong', '自抓四张相同的牌开杠',
      'Created when four identical tiles, all self-drawn, are declared as a Kong.',
      [['w2', 'w2', 'w2', 'w2', -1]], [1, [H.isA, H.isG]]],
    [68, 2, '断幺', 'All Simples', '和牌中没有一、九及字牌', 'A hand formed without Terminal or Honor Tiles.',
      [['w2', 'w3', 'w4'], ['t4', 't5', 't6'], ['b5', 'b6', 'b7'], ['t3', 't4', 't5'], ['b6', 'b6']], [0, 0, H.isNotYOrWord]],
    [69, 1, '一般高', 'Pure Double Chow', '由一种花色的序数相同的顺子组成', 'Two identical chows in the same suit.',
      [['w2', 'w3', 'w4'], ['w2', 'w3', 'w4']], [H.is1ColorNSameS(2)]],
    [70, 1, '喜相逢', 'Mixed Double Chow', '由两种花色的序数相同的顺子组成', 'Two chows of the same numbers but in different suits.',
      [['w2', 'w3', 'w4'], ['t2', 't3', 't4']], [H.isNColorNSameS(2)]],
    [71, 1, '连六', 'Short Straight', '由一种花色六张序数相连的顺子组成',
      'Two chows in the same suit that run consecutively after one another to make a six-tile straight.',
      [['w2', 'w3', 'w4'], ['w5', 'w6', 'w7']], [H.is6InARow]],
    [72, 1, '老少副', 'Two Terminal Chows', '由一种花色的123、789 的顺子组成', 'Chows of 1-2-3 and 7-8-9 in the same suit.',
      [['w1', 'w2', 'w3'], ['w7', 'w8', 'w9']], [[-1, H.isYoung], [-1, H.isOld], [H.isUniqMoreThan(5)]]],
    [73, 1, '幺九刻', 'Pung of Teminals or Honors', '由三张相同的一、九序数牌、字牌组成的刻子',
      'A pung or Kong of Ones, Nines, or Winds. (A dragon pung scores 2 points.)',
      [['w1', 'w1', 'w1'], ['b9', 'b9', 'b9'], ['f2', 'f2', 'f2'], ['j2', 'j2', 'j2']], [1, 0, H.isYOrWord]],
    [74, 1, '明杠', 'Melded Kong', '他人打出一张与暗刻相同的牌开杠；或抓进一张与明刻相同的牌开杠',
      'A kong that was claimed from another player or promoted from a melded pung.',
      [['w2', 'w2', 'w2', 'w2']], [1, [H.isM, H.isG]]],
    [75, 1, '缺一门', 'One Voided Suit', '和牌中缺少一种花色序数牌',
      'A hand that uses tiles from only two of the three suits (it lacks any tiles from one of the three suits).',
      [['w2', 'w2', 'w2'], ['t1', 't2', 't3'], ['t3', 't4', 't5'], ['f3', 'f3', 'f3'], ['w6', 'w6']], [H.is2Color]],
    [76, 1, '无字', 'No Honors', '和牌中没有字牌', 'A hand formed entirely of suit tiles, without Winds or Dragons.',
      [['w2', 'w2', 'w2'], ['t1', 't2', 't3'], ['b5', 'b6', 'b7'], ['t3', 't4', 't5'], ['b6', 'b6']], [0, 0, H.isDigit]],
    [77, 1, '边张', 'Edge Wait', '只能听和123 的3 或789 的7',
      'Waiting solely for a 3 to form a 1-2-3 chow, or solely for a 7 to form a 7-8-9 chow. Not valid if waiting for more than one tile. Not valid if the edge wait is combined with any other waits.',
      [['b1', 'b2', 'b3', 2], ['b7', 'b8', 'b9', 0]], [H.isHSide]],
    [78, 1, '坎张', 'Closed Wait', '只能听和顺子中间的牌',
      'Waiting solely for a tile whose number is "inside" (in the middle) to form a chow. Not valid if waiting for more than one tile. Not valid if the closed wait is combined with other waits.',
      [['b2', 'b3', 'b4', 1]], [H.isHMid]],
    [79, 1, '单调将', 'Single Wait', '调单张牌作将和牌',
      'Waiting solely for a tile to form a pair. Not valid if waiting for more than one tile (for example, holding 1-2-3-4 and waiting on the 1 and 4).',
      [['w5', 'w5', 1]], [H.isHPair]],
    [80, 1, '自摸', 'Self-Drawn', '抓牌成和牌', 'Going out (making mahjong) with a fresh tile picked from the wall.',
      [], [H.isHSelf]],
    [81, 1, '花牌', 'Flower Tiles', '每张花牌计1 分，不计在起和分内，和牌后才能计分。补花成和牌计自摸，不计杠上开花分；未补的花牌允许打出',
      'Each tile carved with Chinese word for Spring, Summer, Autumn, Winter, Plum, Orchid, Bamboo or Chrysanthemum, will award you one point when you succeed in Hu. In case of “Hu” on a Flower replacement, the point for Self-Drawn can be added, but not the points for Out with Replacement Tile. Flower Tiles may be discarded (without taking a replacement).',
      [['h1', 'h2', 'h3', 'h4'], ['h5', 'h6', 'h7', 'h8']]],
  ]
}